name: "port"
description: "Client SDK to interact with Port server."
version: 1.3.1

environment:
  sdk: ^3.6.0

publish_to: none # git dep

dependencies:
  dmrtd:
  #  path: ../dmrtd/dmrtd
  # temp commented out
    git:
      url: https://github.com/ZeroPass/dmrtd.git
  #    ref: develop
  flutter:
    sdk: flutter
  logging: ^1.0.1
  package_info_plus: ^4.1.0
  pointycastle: ^3.7.4
  uuid: ^4.5.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.5