name: "port"
description: "Client SDK to interact with Port server."
version: 1.2.2

environment:
  sdk: '>=2.12.0 <3.0.0'

publish_to: none # git dep

dependencies:
  dmrtd:
    git:
      url: https://github.com/ZeroPass/dmrtd.git
      ref: v1.2.1
  flutter:
    sdk: flutter
  logging: ^1.0.1
  package_info_plus: ^1.0.6
  pointycastle: ^3.0.1
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.3