name: passid
description: PassID protocol.
version: 1.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

publish_to: none # git dep

dependencies:
  dmrtd:
    git:
      url: https://github.com/ZeroPass/dmrtd.git
  flutter:
    sdk: flutter
  logging: ^0.11.4
  pointycastle: ^3.0.1
  uuid: ^2.0.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.3